---
- name: Read the RKE2 kubeconfig from the bootstrap server
  ansible.builtin.command: "sudo cat {{ rke2_kubeconfig_path }}"
  register: rke2_kubeconfig_command
  changed_when: false

- name: Store the exported RKE2 kubeconfig for localhost tasks
  ansible.builtin.set_fact:
    rke2_exported_kubeconfig: "{{ rke2_kubeconfig_command.stdout }}"
