---
- name: Wait until the expected number of RKE2 nodes appears
  ansible.builtin.command: "{{ rke2_kubectl_path }} get nodes -o wide --no-headers"
  check_mode: false
  environment:
    KUBECONFIG: "{{ rke2_kubeconfig_path }}"
  register: rke2_nodes_command
  changed_when: false
  retries: "{{ rke2_cluster_verify_retries }}"
  delay: "{{ rke2_cluster_verify_delay }}"
  until: rke2_nodes_command.stdout_lines | length >= rke2_expected_node_count | int

- name: List cluster nodes
  ansible.builtin.command: "{{ rke2_kubectl_path }} get nodes -o wide"
  check_mode: false
  environment:
    KUBECONFIG: "{{ rke2_kubeconfig_path }}"
  changed_when: false

- name: List cluster pods
  ansible.builtin.command: "{{ rke2_kubectl_path }} get pods -A"
  check_mode: false
  environment:
    KUBECONFIG: "{{ rke2_kubeconfig_path }}"
  changed_when: false
