---
rke2_init_server_script_path: /home/ubuntu/rke2-init-server.sh
rke2_join_server_script_path: /home/ubuntu/rke2-join-server.sh
rke2_join_agent_script_path: /home/ubuntu/rke2-join-agent.sh
rke2_server_token_path: /var/lib/rancher/rke2/server/node-token
rke2_server_service_symlink: /etc/systemd/system/multi-user.target.wants/rke2-server.service
rke2_agent_service_symlink: /etc/systemd/system/multi-user.target.wants/rke2-agent.service
rke2_kubectl_path: /var/lib/rancher/rke2/bin/kubectl
rke2_registration_port: 9345
rke2_kubeconfig_path: /etc/rancher/rke2/rke2.yaml
rke2_cluster_verify_retries: 20
rke2_cluster_verify_delay: 15
